version: '0.4.1.{build}'

environment:
#  global:
      # Example can be found here https://github.com/quantopian/zipline/blob/master/appveyor.yml
#      ANACONDA_TOKEN: # not required anymore since it is configured at AppVeyor
  matrix:
    - PYTHON_LOC: "C:\\Miniconda37-x64"
      PYTHON_VERSION: 3.7

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda install conda-build anaconda-client
  - cmd: conda info -a

build_script:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat root
  - cmd: conda build --old-build-string -c bc-dev -c conda-forge -c anaconda -c bc-dev -c ioos recipes\gridtools
  - cmd: if %APPVEYOR_REPO_BRANCH% == master upload_to_anaconda_cloud %ANACONDA_TOKEN%

