# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

package:
  name: esdl
  version: "0.3.0.dev1"

build:
  number: 0

source:
  git_url: https://github.com/esa-esdl/esdl-core

requirements:
  build:
    - python {{ python }}
    - gridtools ==0.4.1

  run:
    - python {{ python }}
    - numpy >=1.15,<2.0
    - dask >=0.19,<1.0.3
    - gridtools>=0.4.1,<1.0
    - h5netcdf >=0.4.2,<1.0
    - h5py >=2.6.0,<3.0
    - llvmlite >=0.13.0,<1.0
    - netcdf4 >=1.2,<2.0
    - numba >=0.33,<1.0
    - pandas >=0.22,<1.0
    - python-dateutil >=2.6,<3.0
    - pytz >=2016.6.1
    - scikit-image >=0.12.3, <1.0
    - setuptools >=27.2.0
    - six >=1.10.0,<2.0
    - wheel >=0.29.0,<1.0
    - xarray >=0.10.3,<1.0
    - zarr >=2.2.0,<3.0


test:
  # To disable JIT compilation in NUMBA (e.g. for unit-level testing). Make sure that
  # the system env var NUMBA_DISABLE_JIT=1
  script_env:
    - NUMBA_DISABLE_JIT
  imports:
    - esdl
    - esdl.cube_gen
  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov

about:
  home: https://github.com/esa-esdl/esdl-core
  license: MIT
  license_file: LICENSE

